const specialistData = [
  {
    id: 1,
    name: "Mrs. Sarah Geller",
    img: "https://disin-react.hibootstrap.com/images/doctors/doctor1.jpg",
    fb: "https://www.facebook.com/joydey.joydey.16/",
    twitter: "https://twitter.com/JoyDey71740087",
    linkedIn: "https://www.linkedin.com/in/joy-dey-5584841a4/",
    job: "Heart Specialist",
  },
  {
    id: 2,
    name: "Mr. Smith Peter",
    img: "https://disin-react.hibootstrap.com/images/doctors/doctor2.jpg",
    fb: "https://www.facebook.com/joydey.joydey.16/",
    twitter: "https://twitter.com/JoyDey71740087",
    linkedIn: "https://www.linkedin.com/in/joy-dey-5584841a4/",
    job: "Neurosurgeon",
  },
  {
    id: 3,
    name: "Mr. Alinson Backer",
    img: "https://disin-react.hibootstrap.com/images/doctors/doctor3.jpg",
    fb: "https://www.facebook.com/joydey.joydey.16/",
    twitter: "https://twitter.com/JoyDey71740087",
    linkedIn: "https://www.linkedin.com/in/joy-dey-5584841a4/",
    job: "Neurosurgeon",
  },
  {
    id: 4,
    name: "Mr. Lisa Jenson",
    img: "https://disin-react.hibootstrap.com/images/doctors/doctor4.jpg",
    fb: "https://www.facebook.com/joydey.joydey.16/",
    twitter: "https://twitter.com/JoyDey71740087",
    linkedIn: "https://www.linkedin.com/in/joy-dey-5584841a4/",
    job: "Arthopedicts",
  },
  {
    id: 5,
    name: "Mr. Selina Gomez",
    img: "https://disin-react.hibootstrap.com/images/doctors/doctor5.jpg",
    fb: "https://www.facebook.com/joydey.joydey.16/",
    twitter: "https://twitter.com/JoyDey71740087",
    linkedIn: "https://www.linkedin.com/in/joy-dey-5584841a4/",
    job: "Cardiologist",
  },
  {
    id: 6,
    name: "Mr. John Smith",
    img: "https://disin-react.hibootstrap.com/images/doctors/doctor6.jpg",
    fb: "https://www.facebook.com/joydey.joydey.16/",
    twitter: "https://twitter.com/JoyDey71740087",
    linkedIn: "https://www.linkedin.com/in/joy-dey-5584841a4/",
    job: "Darmatologist",
  },
];

export default specialistData;
